version: "3.8"
services:
  bills-web:
    container_name: bills-web
    build:
      context: .
      target: dev
    restart: always
    command: npm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
