apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName}}
  namespace: {{.Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.appName}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{.Values.appName}}
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: {{.Values.appName}}
          image: ghcr.io/yarsoniy/bills-web:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
