import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { Container, CssBaseline } from '@mui/material';

export const metadata: { description: string; title: string } = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
} : {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
        <CssBaseline />
        <Container>
          {children}
        </Container>
      </body>
    </html>
  );
}
